UserLogin/urls.py
from django.conf.urls import url

from . import views

app_name = 'UserLogin'

urlpatterns = [

	url(r'^$',views.indexView,name='home'),
	
	url(r'^register/$',views.registerView,name='register'),

	url(r'^login/$',views.loginView,name='login'),
]

itws3/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sensors/', include('sensors.urls')),
    url(r'^',include('UserLogin.urls'))
]

sensors/urls.py
from django.conf.urls import url
from . import views

app_name = 'sensors'

urlpatterns = [

    url(r'^$', views.index,name='index'),

    url(r'^macroreading/$',views.macroSensorView,name='macro'),

    url(r'^microreading/$',views.microSensorView,name='micro'),

    url(r'^addplant/$', views.addPlants,name='addPlants'),

    url(r'^userprofile/$',views.userprofile,name='userprofile'),

    url(r'^addmicroreading/(?P<plant_id>[0-9]+)/$', views.add_reading_micro),

    url(r'^addmacroreading/$', views.add_reading_macro),

]

sensors/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from UserLogin.models import UserProfile

# addPlant signifies creating a plant which is linked to a particular User
class Plant(models.Model):
    name = models.CharField(max_length=100)
    plant_id = models.AutoField(primary_key=True)
    Latitude = models.FloatField(null=True)
    Longitude = models.FloatField(null=True)
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user) + ' Plant: ' + str(self.plant_id) + ' Lat: ' + str(self.Latitude) + ' Long: ' + str(self.Longitude)

class MicroSensor(models.Model):
    micro_id = models.AutoField(primary_key=True)
    plant = models.ForeignKey(Plant, on_delete=models.CASCADE,null=True)
    SoilMoisture = models.FloatField(null = True)

    def __str__(self):
        return 'SoilMoisture ' + str(self.SoilMoisture) + " " +str(self.plant)

class MacroSensor(models.Model):
    macro_id = models.AutoField(primary_key=True)
    read_time = models.DateField(auto_now=True)
    Temperature = models.FloatField(null = True)
    Humidity = models.FloatField(null = True)
    WaterLevel = models.FloatField(null=True)
    Rain = models.FloatField(null = True)
    Latitude = models.FloatField(null=True)
    Longitude = models.FloatField(null=True)

    def __str__(self):
        return 'Temperature ' + str(self.Temperature) + 'C - Humidity' + str(self.Humidity) + '% - WaterLevel' + str(self.WaterLevel) + 'cm' + ' Rain ' + str(self.Rain) +'cm'

sensors/views.py
from django.http import HttpResponse,HttpResponseRedirect
from .models import MacroSensor,Plant,MicroSensor
from UserLogin.models import UserProfile
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.decorators import login_required
import datetime

@login_required
def index(request):
    mydate = datetime.datetime.now()
    template = 'sensors/index.html'
    microsensor = MicroSensor.objects.filter(plant__user__user=request.user)
    plants = Plant.objects.filter(user__user=request.user)
    return render(request,template,{'username':request.user,'microsensor':microsensor,'plants':plants,'Currdate':mydate.strftime("%B %d, %Y")})

@login_required
def macroSensorView(request):
    macrosensors=MacroSensor.objects.all()
    template = 'sensors/macro.html'
    context={
        'macrosensors':macrosensors,
        'user':request.user,
    }
    return render(request,template,context)

@login_required
def microSensorView(request):
    mydate = datetime.datetime.now()
    plants=Plant.objects.filter(user__user=request.user)
    microsensors={}
    for plant in plants:
        plant_id = plant.plant_id
        for microObj in MicroSensor.objects.filter(plant__user__user=request.user):
            plant_test_id=microObj.plant.plant_id
            if(plant_test_id == plant_id):
                microsensors.setdefault(str(plant_id),[])
                microsensors[str(plant_id)].append(microObj)

    template = 'sensors/micro.html'
    context = {
        'plants': plants,
        'user':request.user,
        'microsensors':microsensors,
        'Currdate':mydate.strftime("%B %d, %Y")
    }
    return render(request,template,context)

@login_required
@csrf_exempt
def addPlants(request):
    template = 'sensors/addplant.html'
    if(request.method == 'POST'):
        user = UserProfile.objects.get(user = request.user)
        plant = Plant()
        plant.user = user
        plant.Latitude = float(request.POST.get('lat'))
        plant.Longitude = float(request.POST.get('long'))
        plant.name = request.POST.get('name')
        plant.save()
        microsensor = MicroSensor()
        microsensor.plant = plant
        microsensor.save()

        return HttpResponseRedirect(reverse('sensors:index'))
    else:
        return render(request,template)

@csrf_exempt
def add_reading_macro(request):
    if request.POST.get('temp') :
        new_reading = MacroSensor()
        new_reading.Temperature = request.POST.get('temp')
        new_reading.Humidity = request.POST.get('hum')
        new_reading.WaterLevel = request.POST.get('watL')
        new_reading.Rain = request.POST.get('rainG')
        new_reading.save()

        return HttpResponse(status=200)
    return  HttpResponse(status=400)


@csrf_exempt
def add_reading_micro(request,plant_id):

    if request.POST.get('soilM'):
        plant = get_object_or_404(Plant,pk=plant_id)
        new_reading= MicroSensor()
        new_reading.plant = plant
        new_reading.SoilMoisture = request.POST.get('soilM')
        new_reading.save()

        return HttpResponse(status=200)
    return  HttpResponse(status=400)

@csrf_exempt
def userprofile(request):
    template = 'sensors/userprofile.html'
    plants = Plant.objects.filter(user__user=request.user)
    context = {
        'plants': plants,
        'user': request.user,
    }
    if(request.method == 'POST'):
        name1 = request.POST.get('name')
        plants = Plant.objects.filter(user__user=request.user)
        for plant in plants:
            if(plant.name == request.POST.get('name')):
                plant.delete()
                break
            if(plant.name == request.POST.get('name1')):
                plant.Latitude = float(request.POST.get('lat1'))
                plant.Longitude = float(request.POST.get('long1'))
                plant.save()

        return HttpResponseRedirect(reverse('sensors:index'))
    else:
        return render(request, template, context)

sensors/templates/sensors/addplant.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- These meta tags come first. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Add Plant</title>

    <!-- Include the CSS -->
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>

    <link href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic" rel="stylesheet">

      <link href="{% static "assets/css/toolkit-inverse.css" %}" rel="stylesheet">
      <link href="{% static "assets/css/application.css" %}" rel="stylesheet">
      <link href="{% static "dist/toolkit.min.css" %}" rel="stylesheet">
      <style>
      .bord{
        border-color: blue;
        border-width: 2px;
      }
    </style>

  </head>
  <body>
   <nav class="iconav">
    <a class="iconav-brand" href="{% url 'UserLogin:home' %}">
      <span class="icon icon-leaf iconav-brand-icon"></span>
    </a>
    <div class="iconav-slider">
      <ul class="nav nav-pills iconav-nav flex-md-column">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'sensors:index' %}" title="Home" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-home"></span>
            <small class="iconav-nav-label hidden-md-up">Home</small>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'sensors:addPlants' %}" title="Add Plants" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-flower"></span>
            <small class="iconav-nav-label hidden-md-up"> Add Plants</small>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'sensors:macro' %}" title="Macrosensors" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-drop"></span>
            <small class="iconav-nav-label hidden-md-up">Macrosensors</small>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'sensors:micro' %}" title="Microsensors" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-area-graph"></span>
            <small class="iconav-nav-label hidden-md-up">Microsensors</small>
          </a>
        </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'sensors:userprofile' %}" title="Signed in as {{ user.username}}" data-toggle="tooltip" data-placement="right" data-container="body">
             <span class="icon icon-user"></span>
            <small class="iconav-nav-label hidden-md-up">@mdo</small>
          </a>
          </li>
            <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLogin:home' %}" title="Log Out" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-log-out"></span>
            <small class="iconav-nav-label hidden-md-up">Log Out</small>
          </a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container">
    <div class="dashhead">
      <div class="dashhead-titles">
        <h6 class="dashhead-subtitle">Water Management System</h6>
        <h3 class="dashhead-title">Add Plant</h3>
      </div>

      <br>
      <br>
      <br><br>
   <center>


<h1 class="display-3">Welcome To Add Plants Page {{ user.username }}</h1>
     <br>
  <p class="lead">Click the button below to add a plant to the system.</p>

       <button class="btn btn-lg btn-outline-success" onclick="myFunction()">Click me</button><h3 id="demo"></h3>
</center>
        <br><br>
        <div id="map" style="display : none">
          <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4">
      <form action="{% url 'sensors:addPlants' %}" method="post">
        <input type="text" class="form-control" required autocomplete="off" placeholder="Name" name="name" />  <br><br>
        <input type="text" class="form-control" required autocomplete="off" placeholder="Latitude" name="lat" />  <br><br>
        <input type="text" class="form-control" required autocomplete="off" placeholder="Longitude" name="long" /><br><br>
        <center>
        <button type="submit" class="btn btn-lg btn-outline-success">Submit</button>
        </center>
        </form>
        </div>

    </div>
    </div>
      <br><br>
    <!-- Include jQuery (required) and the JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <script src="{% static "assets/js/jquery.min.js" %}"></script>
    <script src="{% static "assets/js/tether.min.js" %}"></script>
       <script src="{% static "assets/js/chart.js" %}"></script>
    <script src="{% static "assets/js/tablesorter.min.js" %}"></script>
    <script src="{% static "assets/js/toolkit.js" %}"></script>
    <script src="{% static "assets/js/application.js" %}"></script>
    <script>
      // execute/clear BS loaders for docs
      $(function(){while(window.BS&&window.BS.loader&&window.BS.loader.length){(window.BS.loader.pop())()}})
    </script>
      <script>
function myFunction() {
    document.getElementById("demo").innerHTML = "<br><br>Enter the location co-ordinates of your Plant.";
    $("#map").css("display","block");
}
</script>
      <script>
        function divshow(){

        }
      </script>

  </body>
<!---
</html>

sensors/templates/sensors/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- These meta tags come first. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Home Page</title>

    <!-- Include the CSS -->
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <link href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic" rel="stylesheet">

      <link href="{% static "assets/css/toolkit-inverse.css" %}" rel="stylesheet">
      <link href="{% static "assets/css/application.css" %}" rel="stylesheet">
      <link href="{% static "dist/toolkit.min.css" %}" rel="stylesheet">
      <style>
      #map {
        height: 100%;
        width:100%;
      }
      .bord{
        border-color: blue;
        border-width: 2px;
      }
      #shape{
      width:200px;
      height:200px;
      border-radius:20px;
      border-width:20px;
      border-color:black;
      background-color:red;
      }
       .hape{
      width:20px;
      height:20px;
      border-radius:2px;
      border-width:10px;
      border-color:black;
      background-color:red;
      }
    </style>

  </head>
  <body>
   <nav class="iconav">
    <a class="iconav-brand" href="{% url 'UserLogin:home' %}">
      <span class="icon icon-leaf iconav-brand-icon"></span>
    </a>
    <div class="iconav-slider">
      <ul class="nav nav-pills iconav-nav flex-md-column">
        <li class="nav-item">
          <a class="nav-link active" href="" title="Home" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-home"></span>
            <small class="iconav-nav-label hidden-md-up">Home</small>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'sensors:addPlants' %}" title="Add Plants" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-flower"></span>
            <small class="iconav-nav-label hidden-md-up"> Add Plants</small>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'sensors:macro' %}" title="Macrosensors" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-drop"></span>
            <small class="iconav-nav-label hidden-md-up">Macrosensors</small>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'sensors:micro' %}" title="Microsensors" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-area-graph"></span>
            <small class="iconav-nav-label hidden-md-up">Microsensors</small>
          </a>
        </li>
       <li class="nav-item">
          <a class="nav-link" href="{% url 'sensors:userprofile' %}" title="Signed in as {{ user.username}}" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-user"></span>
            <small class="iconav-nav-label hidden-md-up">@mdo</small>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLogin:home' %}" title="Log Out" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-log-out"></span>
            <small class="iconav-nav-label hidden-md-up">Log Out</small>
          </a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container">
    <div class="dashhead">
      <div class="dashhead-titles">
        <h6 class="dashhead-subtitle">Water Management System</h6>
        <h3 class="dashhead-title">Home</h3>
      </div>

      <div style="align:left"  class="dashhead-toolbar">
        <div class="input-with-icon dashhead-toolbar-item">
          <h3>Welcome</h3>
        </div>
        <span class="dashhead-toolbar-divider hidden-sm-down"></span>
        <div class="btn-group dashhead-toolbar-item btn-group-thirds">
                    <button type="button" class="btn btn-outline-primary">User :</button>
          <button type="button" class="btn  btn-outline-primary active">{{ user.username }}</button>
        </div>
      </div>
    </div>
    <br>

        <br>
    <br>
    <div class="dashhead"></div>
    <div class="flextable">
  <div class="flextable-item flextable-primary">
    <input type="text" class="form-control" placeholder="Plant Location">
  </div>
  <div class="flextable-item">
    <div class="btn-group">
      <button type="button" class="btn btn-outline-primary">
        <span class="icon icon-pencil"></span>
      </button>
      <button type="button" class="btn btn-outline-primary">
        <span class="icon icon-erase"></span>
      </button>
    </div>
  </div><br><br>

  <br>
  <div id="map" style="width:100%;height:400px;"></div>
      <br/><br/>
<br>  <div class="list-group mb-3 bord">
  <h6 class="list-group-header">
    Announcements
  </h6>

    <a class="list-group-item list-group-item-action justify-content-between" href="#">
      <span>Hello! The alpha version of our project is now up and running. We are very excited to have you as one of our alpha testers. We hope to impress you with the new features and the updated UI. We hope the product works as well as we intended.Looking forward to your feedback!</span>
      <span class="text-muted">10 Oct 2017</span>
    </a>

</div>
</div>
</div>
    <!-- Include jQuery (required) and the JS -->
   <script>

        var LATITUDE=13.557158;
        var LONGITUDE=80.025031;
      function initMap() {
        var myLatLng = {lat: LATITUDE, lng: LONGITUDE};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 11,
          center: myLatLng,
          gestureHandling: 'cooperative'
        });

        var marker
        {% for plant in plants %}

           marker = new google.maps.Marker({
            position: new google.maps.LatLng(parseFloat('{{plant.Latitude}}'),parseFloat('{{plant.Longitude}}')),
            map:map
          });

        {% endfor %}
        marker.addListener('click', toggleBounce);
      }
      function toggleBounce() {
        if (marker.getAnimation() !== null) {
          marker.setAnimation(null);
        } else {
          marker.setAnimation(google.maps.Animation.BOUNCE);
        }
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCKciRbMXkD9mcYb_0_CHKAWjENhO44a8k&&callback=initMap">
      //google.maps.event.addDomListener(window, 'load', initialize);
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <script src="{% static "assets/js/jquery.min.js" %}"></script>
    <script src="{% static "assets/js/tether.min.js" %}"></script>
       <script src="{% static "assets/js/chart.js" %}"></script>
    <script src="{% static "assets/js/tablesorter.min.js" %}"></script>
    <script src="{% static "assets/js/toolkit.js" %}"></script>
    <script src="{% static "assets/js/application.js" %}"></script>
    <script>
      // execute/clear BS loaders for docs
      $(function(){while(window.BS&&window.BS.loader&&window.BS.loader.length){(window.BS.loader.pop())()}})
    </script>
  </body>
</html>

sensors/templates/sensors/userprofile.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- These meta tags come first. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Add Plant</title>

    <!-- Include the CSS -->
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>

    <link href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic" rel="stylesheet">

      <link href="{% static "assets/css/toolkit-inverse.css" %}" rel="stylesheet">
      <link href="{% static "assets/css/application.css" %}" rel="stylesheet">
      <link href="{% static "dist/toolkit.min.css" %}" rel="stylesheet">
      <style>
      .bord{
        border-color: blue;
        border-width: 2px;
      }
    </style>

  </head>
<body>
    <nav class="iconav">
    <a class="iconav-brand" href="{% url 'UserLogin:home' %}">
      <span class="icon icon-leaf iconav-brand-icon"></span>
    </a>
    <div class="iconav-slider">
      <ul class="nav nav-pills iconav-nav flex-md-column">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'sensors:index' %}" title="Home" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-home"></span>
            <small class="iconav-nav-label hidden-md-up">Home</small>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'sensors:addPlants' %}" title="Add Plants" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-flower"></span>
            <small class="iconav-nav-label hidden-md-up"> Add Plants</small>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'sensors:macro' %}" title="Macrosensors" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-drop"></span>
            <small class="iconav-nav-label hidden-md-up">Macrosensors</small>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'sensors:micro' %}" title="Microsensors" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-area-graph"></span>
            <small class="iconav-nav-label hidden-md-up">Microsensors</small>
          </a>
        </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'sensors:userprofile' %}" title="Signed in as {{ user.username}}" data-toggle="tooltip" data-placement="right" data-container="body">
             <span class="icon icon-user"></span>
            <small class="iconav-nav-label hidden-md-up">@mdo</small>
          </a>
          </li>
            <li class="nav-item">
          <a class="nav-link" href="{% url 'UserLogin:home' %}" title="Log Out" data-toggle="tooltip" data-placement="right" data-container="body">
            <span class="icon icon-log-out"></span>
            <small class="iconav-nav-label hidden-md-up">Log Out</small>
          </a>
        </li>
      </ul>
    </div>
  </nav>
    <center>
    <h1 class="display-3">Welcome To Plants Page <br>{{ user.username }}</h1>
        <br><br>



<h2> You have the following plants</h2>
<br> <br>
         <div class="container">
        <table class="table table-hover">
                      <thead>
                        <tr>
                          <th>Plant Name</th>
                          <th>Latitude</th>
                          <th>Longitude</th>
                        </tr>
                      </thead>

                      <tbody>
                        <tr  {% for plant in plants %}>
                          <td>
                            {{ plant.name }}
                          </td>
                          <td>
                            {{ plant.Latitude }}
                          </td>
                          <td>
                            {{ plant.Longitude }}
                          </td>
                        </tr {% endfor %}>
                      </tbody>
                    </table>
                </div>





    <br><br> <br><br>

        <div class="container">
     <div class="row">
      <div class="col s5">
    <button type="button" class="btn btn-lg btn-outline-danger" data-toggle="collapse" data-target="#wowo">Delete Plant</button>
    <div id="wowo" class="collapse">
    <br><br>
         <h3>Enter the name of the plant you want to delete</h3>
         <div class="col-sm-6"></div>
         <div class="col-sm-6">
        <form action="{% url 'sensors:userprofile' %}" method="post">
        <input type="text" class="form-control" required autocomplete="off" placeholder="Name" name="name" />  <br><br>
        <button type="submit" class="btn btn-outline-success">Delete</button>
        </form>
      </div>
      </div>
      </div>

    <br><br> <br><br>

        <div class="col s5">
     <button type="button" class="btn btn-lg btn-outline-primary" data-toggle="collapse" data-target="#wow">Update Plant</button>
     <div id="wow" class="collapse">
     <br><br>
        <h3>Update Plant Details</h3>
        <br><br>
        <div class="col-sm-6"></div>
        <div class="col-sm-6">
            <form action="{% url 'sensors:userprofile' %}" method="post">
                <input type="text" class="form-control" required autocomplete="off" placeholder="Name" name="name1" />  <br><br>
                <input type="text" class="form-control" required autocomplete="off" placeholder="Latitude" name="lat1" />  <br><br>
                <input type="text" class="form-control" required autocomplete="off" placeholder="Longitude" name="long1" /><br><br>
                <button type="submit" class="btn btn-outline-success">Update</button>
            </form>
          </div>
            </div>
            </div>
            </div>
            </div>
       <div class="container">
    </center>
</body>
</html>