UserLogin/urls.py
from django.conf.urls import url

from . import views

app_name = 'UserLogin'

urlpatterns = [

	url(r'^$',views.indexView,name='home'),
	
	url(r'^register/$',views.registerView,name='register'),

	url(r'^login/$',views.loginView,name='login'),
]

itws3/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sensors/', include('sensors.urls')),
    url(r'^',include('UserLogin.urls'))
]

UserLogin/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
# Create your models here.

# We have created an extension(one to one relationship) of inbuilt user models provided by django
class UserProfile(models.Model):
    user = models.OneToOneField(User)

    def __str__(self):
        return 'Username: ' + str(self.user)

UserLogin/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm,PasswordInput
from .models import *
import forms

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password','first_name','last_name')

UserLogin/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponseRedirect
from .models import UserProfile
from django.urls import reverse
from django.contrib.auth.models import User
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login,logout
from .forms import UserForm
from django.views import generic
from django.views.decorators.csrf import csrf_exempt


def indexView(request):
	logout(request)
	template_name='UserLogin/home.html'
	return render(request,template_name)

@csrf_exempt
def registerView(request):
    logout(request)
    if request.method=='POST':
        form=UserForm(request.POST)
        if form.is_valid():
            new_user = User.objects.create_user(**form.cleaned_data)
            new_user_profile = UserProfile()
            new_user_profile.user = new_user
            new_user_profile.save()
            login(request,new_user)
            return HttpResponseRedirect('/sensors/')
    else:
        form=UserForm()

    return render(request,'UserLogin/registration_form.html',{'form':form})                        

@csrf_exempt
def loginView(request):
    logout(request)
    if request.method=='POST':
        form=UserForm(request.POST)
        try:
            username=request.POST.get('username')
            password=request.POST.get('password')
            user = authenticate(username=username,password=password)
            login(request,user)
            return HttpResponseRedirect('/sensors/')
        except Exception:
            return HttpResponseRedirect(reverse('UserLogin:login'))
    else:
        form = UserForm()
    return render(request,'UserLogin/login_form.html',{'form':form})

UserLogin/templates/UserLogin/home.html
{% load static %}
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>Water And Plant Management</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static "css/materialize.css" %}"type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static "css/style1.css" %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link rel="stylesheet" type="text/css" href="{% static "css/materialize.css" %}" />
  <link rel="stylesheet" type="text/css" href="{% static "css/materialize.min.css" %}" />
  <link rel="stylesheet" type="text/css" href="{% static "css/style1.css" %}" />
  <link rel="stylesheet" type="text/css" href="{% static "js/init.js" %}" />
  <link rel="stylesheet" type="text/css" href="{% static "css/materialize.js" %}" />
  <link rel="stylesheet" type="text/css" href="{% static "css/materialize.min.css" %}" />
</head>
<body>
  <nav class="navbar-fixed teal "  role="navigation">
    <div class="nav-wrapper container" >
      <a id="logo-container" href="" class="brand-logo">Plant Monitoring System</a>
      <ul class="right hide-on-med-and-down" style="color:black">
        <li><a href="{% url 'UserLogin:login' %}">Log-In</a></li>
        <li><a href="{% url 'UserLogin:register' %}"">Sign-Up</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="{% url 'UserLogin:login' %}">Log-In</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center teal-text text-darken-2">Plant Managment System</h1>
        <div class="row center">
          <h3 class="header col s12 dark">Group 5</h3>
        </div>
        <div class="row center">
          <a href="{% url 'UserLogin:register' %}" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Planting-Sign Up</a>
        </div>
        <br><br>

      </div>
    </div>
    <div class="parallax"><img src="{% static "images/background1.jpg" %}" class="z-depth-2"></div>
  </div>


  <div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">flash_on</i></h2>
            <h5 class="center">Responsive User Interface</h5>

            <p class="light">
            A fully responsive user interface with interactive graphs for multi-platform usability and a vibrant experience.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">group</i></h2>
            <h5 class="center">User Oriented Database</h5>

            <p class="light">Your experience is personalised, and your settings and plants will be completely secure, and all setting tailored for you. </p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Robust Hardware Design</h5>

            <p class="light">Every single component of hardware used is precisely integrated with the software, so both work fluidly to give you the best experience.</p>
          </div>
        </div>
      </div>

    </div>
  </div>
  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light">"A man doesn't plant a tree for himself.He plants it for posterity."<br>-Alexander Smith </h5>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="{% static "images/background2.jpg" %}" ></div>
  </div>
  <div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12 center">
          <h3><i class="mdi-content-send brown-text"></i></h3>
          <h4>Contact Us</h4>
          <p class="left-align light"><br>Arvind Deshraj: <a class="brown-text text-lighten-3" href="https://mail.google.com/mail/?view=cm&fs=1&to=arvind.d16@iiits.in" target="_blank">arvind.d16@iiits.in</a><br>Srijan Reddy: <a class="brown-text text-lighten-3" href="https://mail.google.com/mail/?view=cm&fs=1&to=srijanreddy.v16@iiits.in" target="_blank">srijanreddy.v16@iiits.in</a><br>Rishav Varma: <a class="brown-text text-lighten-3" href="https://mail.google.com/mail/?view=cm&fs=1&to=rishavchandra.v16@iiits.in" target="_blank">rishavchandra.v16@iiits.in</a><br>Sahaj Agarwal: <a class="brown-text text-lighten-3" href="https://mail.google.com/mail/?view=cm&fs=1&to=sahaj.a16@iiits.in" target="_blank">sahaj.a16@iiits.in</a><br>Uday Sawhney:<a class="brown-text text-lighten-3" href="https://mail.google.com/mail/?view=cm&fs=1&to=udayraj.s16@iiits.in" target="_blank"> udayraj.s16@iiits.in</a><br>Rutvik Vijjali:<a class="brown-text text-lighten-3" href="https://mail.google.com/mail/?view=cm&fs=1&to=rutvikreddy.v16@iiits.in" target="_blank"> rutvikreddy.v16@iiits.in</a></p>
        </div>
      </div>

    </div>
  </div>

  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
          <h5 class="white-text">Project Details</h5>
          <p class="grey-text text-lighten-4">This project has been made under the guidance of Prof. Nagesh Kolagani.</p>


      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Copyrights of <a class="brown-text text-lighten-3" href="http://climit.16mb.com">Climit</a>
      </div>
    </div>
  </footer>
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static "js/materialize.js" %}"></script>
  <script src="{% static "js/init.js" %}"></script>

  </body>
</html>

UserLogin/templates/UserLogin/login_form.html
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'sensors/style.css' %}" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>




 <head>
<meta charset="UTF-8">
  <title>Sign-up</title>
  <link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

      <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
<form action="{% url 'UserLogin:login' %}" method="POST">

  <div class="container form">

    <h1>Log In</h1>

          <div class="field-wrap">
            <label>
              User name<span class="req">*</span>
            </label>
            <input type="text" required autocomplete="off" name="username" />
          </div>

          <div class="field-wrap">
            <label>
              Password<span class="req">*</span>
            </label>
            <input type="password" required autocomplete="off" name="password"/>
          </div>

          <button type="submit" class="button button-block"/>Login</button>
          <br><center><span style="color:white">Don't have an account ? </span><a href="{% url 'UserLogin:register' %}">Sign Up</a></center>
  </div>
</form>
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

  <script  src="{% static 'js/index.js' %}"></script>
</body>

UserLogin/templates/UserLogin/registration_form.html
{% load static %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
<link href='https://fonts.googleapis.com/css?family=Satisfy' rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'sensors/style.css' %}" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>



 <head>
<meta charset="UTF-8">
  <title>Sign-up</title>
  <link href='https://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

      <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
<form action="{% url 'UserLogin:register' %}" method="POST">

  <div class="container form">

    <h1>Register</h1>

            <div class="field-wrap">
            <label>
              First name<span class="req">*</span>
            </label>
            <input type="text" required autocomplete="off" name="first_name" />
          </div>

          <div class="field-wrap">
            <label>
              Last name<span class="req">*</span>
            </label>
            <input type="text" required autocomplete="off" name="last_name" />
          </div>

          <div class="field-wrap">
            <label>
              User name<span class="req">*</span>
            </label>
            <input type="text" required autocomplete="off" name="username" />
          </div>

          <div class="field-wrap">
            <label>
              Email<span class="req">*</span>
            </label>
            <input type="email" required autocomplete="off" name="email" />
          </div>

          <div class="field-wrap">
            <label>
              Password<span class="req">*</span>
            </label>
            <input type="password" required autocomplete="off" name="password"/>
          </div>

          <button type="submit" class="button button-block"/>Register</button>
          <br><center><span style="color:white">Already  a  user ? </span><a href="{% url 'UserLogin:login' %}">Login</a></center>
  </div>
</form>
  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

  <script  src="{% static 'js/index.js' %}"></script>
</body>